[build]
publish = "public/"
command = """
export TZ=Australia/Adelaide
pip3 install -q poetry &&
poetry config virtualenvs.in-project true &&
poetry install &&
yarn install &&
yarn run build &&
mkdir -p data/Session &&
poetry run statik &&
cp _redirects public/
"""

[[redirects]]
from = "/schedule/*"
to = "/program/:splat"

[[redirects]]
from = "/tips/"
to = "/speakers/tips/"

[[redirects]]
from = "/backstage/"
to = "/speakers/backstage/"

[[redirects]]
from = "/speakers/*"
to = "/speakers/"

[[redirects]]
from = "/shirt/"
to = "https://www.redbubble.com/people/pyconau/shop"

[[redirects]]
from = "/safety/"
to = "/conduct/"
